// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using equipmentManagement.infra.data.input;

#nullable disable

namespace equipmentManagement.infra.data.input.Migrations
{
    [DbContext(typeof(ContextequipmentManagement))]
    [Migration("20240101160835_FirstMigration")]
    partial class FirstMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("equipmentManagement.infra.data.input.entityTypeConfiguration.models.ProductModel", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(36)
                        .HasColumnType("CHAR");

                    b.Property<int>("Code")
                        .ValueGeneratedOnAdd()
                        .IsUnicode(true)
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Code"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("VARCHAR");

                    b.Property<DateTime?>("ExpirationDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ManufacturingDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("SupplierId")
                        .HasMaxLength(36)
                        .HasColumnType("CHAR");

                    b.HasKey("Id");

                    b.HasIndex("SupplierId");

                    b.ToTable("Product", (string)null);
                });

            modelBuilder.Entity("equipmentManagement.infra.data.input.entityTypeConfiguration.models.SupplierModel", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(36)
                        .HasColumnType("CHAR");

                    b.Property<int>("Code")
                        .ValueGeneratedOnAdd()
                        .IsUnicode(true)
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Code"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("VARCHAR");

                    b.HasKey("Id");

                    b.ToTable("Supplier", (string)null);
                });

            modelBuilder.Entity("equipmentManagement.infra.data.input.entityTypeConfiguration.models.ProductModel", b =>
                {
                    b.HasOne("equipmentManagement.infra.data.input.entityTypeConfiguration.models.SupplierModel", null)
                        .WithMany()
                        .HasForeignKey("SupplierId");
                });

            modelBuilder.Entity("equipmentManagement.infra.data.input.entityTypeConfiguration.models.SupplierModel", b =>
                {
                    b.OwnsOne("equipmentManagement.domain.objectValues.CNPJ", "CNPJ", b1 =>
                        {
                            b1.Property<string>("SupplierModelId")
                                .HasColumnType("CHAR(36)");

                            b1.Property<string>("Number")
                                .IsRequired()
                                .HasMaxLength(14)
                                .HasColumnType("VARCHAR")
                                .HasColumnName("cnpj");

                            b1.HasKey("SupplierModelId");

                            b1.ToTable("Supplier");

                            b1.WithOwner()
                                .HasForeignKey("SupplierModelId");
                        });

                    b.Navigation("CNPJ")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
